#ServerPort
server:
  port: 8001
#  ssl:
#    enable: true
#    key-store: ./keystore.p12
#    key-store-type: PKCS12
#    key-store-password: rlaeodus95

#DataSource
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@soda_low?TNS_ADMIN=./src/main/resources/Wallet_SODA
    username: SODA
    password: Rlaeodus1130
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: create
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: /Users/dykim/Downloads

#AI api
api:
  recommand:
    url: http://192.168.0.173:5050/returnRecommend

#JWT
jwt:
  header: Authorization
  secret: rutyweorituwyerotiuweyrtoiuweyrtoweiurtywoeighdfsojkghsdfgsdofiguwyertouw | base64YWprbGdoc2Rma2xnanNkaGZnbGprc2RmZ2hsc2
  access-token-validity-in-seconds: 43200 #12 hours

